### PR TITLE
Display config DataDirectoryPath after app name in Title bar

### PR DESCRIPTION
**Pull request by mwherman2000**
Display config DataDirectoryPath after app name in Title bar to indicate which set of JSON configuration files are being used.

In MainForm.cs, add the following single line of code to the end of the constructor:

`this.Text += " - " + (String.IsNullOrEmpty(Settings.Default.DataDirectoryPath) ? "---" : Settings.Default.DataDirectoryPath);`

### CODE REVIEW

**Comment by mwherman2000** [comment]
Added a second set of changes to the fork: Added config.neodocker.json and protocol.neodocker.json to the project to support communications with the  NEO privatenet Docker container (https://hub.docker.com/r/metachris/neo-privnet-with-gas/). The original (default) config.json and protocol.json remain unchanged.

**Comment by mwherman2000** [comment]
Added a third set of changes to implement "smart message" formatting in the Event Log:

https://github.com/mwherman2000/neo-windocs/blob/master/windocs/windocs-presentations/images/Transactions2Log.png

Note the "smart messages" on the left side of the log. I add some heuristics to neo-gui-developer to format the messages based on what it thinks the array of bytes is supposed to represent it.  It's kind of cool.  No more "billions of bytes" with no obvious meaning.

The neo-gui event log now knows about account addresses, private keys, WIFs, public keys, etc. and produces smarter formatting of those values.

**Comment by igormcoelho** [comment]
This is a very nice contribution! Congratulations! Hope it gets accepted soon :)

**Review by ghost — CHANGES_REQUESTED** [review]
thanks for the PR - i would suggest that you leave config.json and protocol.json still pointing at testnet rather than the docker config as setting up privnet requires another step by the user to make this app work

**Comment by mwherman2000** [comment]
Added support for $FOO format specifiers in arg[0] of Runtime.Notify calls.  Checkout https://github.com/mwherman2000/neo-windocs/blob/master/windocs/windocs-presentations/images/BlockTxNumbers1.png

**Comment by mwherman2000** [comment]
@birmas, I didn't change the default config.json nor protocol.json.  I'm only requested the addition of the 2 new privatenet versions of the file (with separate names).

...or did I by mistake send up a pair of changed config.json nor protocol.json files too?? ...it wasn't my intention.  Let me know.

**Review by ghost — APPROVED** [review]

**Comment by mwherman2000** [comment]
Remerged all of my changes

**Comment by mwherman2000** [comment]
I think everything is synced up. Please accept these changes.

**Pull request merged**
